version: '3'
services:
  web:
    depends_on:
      - mongodb
    image: aovi
    container_name: aovi-web
    ports:
    # 3000:3000
      - "1041:3000"
    environment:
      - DOCKER=true
      - JWT_SECRET_FILE=/run/secrets/jwt_secret
      - SUPERADMIN_DEFAULT_PASSWORD=${SUPERADMIN_DEFAULT_PASSWORD}  # Pass from shell
    volumes:
      - jwt_secret_volume:/run/secrets
    restart: always
  mongodb:
    image: mongo
    container_name: aovi-mongodb
    restart: always
    volumes:
      - aovi-mongodb-data:/data/db

volumes:
  aovi-mongodb-data:
  jwt_secret_volume: